### ISSUE TITLE
Install Rescapp on non-free Debian Live LXQT Buster

### ISSUE THREAD

**Issue by cjg67** [rescatux/rescatux#100]
Hello Adrian,

You closed that thread when I was in the middle of commenting.
debian-live-10.1.0-amd64-lxqt+nonfree.iso is not usable.  There is no keyboard or mouse and the developer refuses to admit this.
I downloaded Fedora-LXQt-Live-x86_64-30-1.2.iso and that cleanly boots and has an operational keyboard and mouse.  They have added the binary blobs for the firmware into their iso, so there is all the resolutions available.

It is inexcusable to state that something fully works when it does not.  Perhaps that maintainer does not think a keyboard or mouse is necessary, but I certainly do.

Regards,

Christopher.

**Comment by adrian15** [comment]
> debian-live-10.1.0-amd64-lxqt+nonfree.iso is not usable.
> There is no keyboard or mouse and the developer refuses to admit this.

Well, that might a bug that can be reported to Debian. I can teach you via irc how to create the email thanks to reportbug in the live cd and use it from gmail.

It would be nice if we could know when the 'keyboard or mouse do not work' problem happens. (In the normal versions that drop you to the console just write startx to get to the graphical environment.)

* debian-live-10.0.0-amd64-lxqt+nonfree.iso
* debian-live-10.1.0-amd64-lxqt+nonfree.iso
* debian-live-10.0.0-amd64-lxqt.iso
* debian-live-10.1.0-amd64-lxqt.iso

that way we can narrow it to the Debian version or the nonfree additions.

Even if we don't report it to Debian knowing that debian-live-10.0.0-amd64-lxqt+nonfree.iso works for you will be a major step forward.

**Comment by adrian15** [comment]
> I downloaded Fedora-LXQt-Live-x86_64-30-1.2.iso and that
>  cleanly boots and has an operational keyboard and mouse.
> They have added the binary blobs for the firmware into their iso,
> so there is all the resolutions available.

Are you that they have added those binary blobs. I didn't think that Fedora was so "non-free". Did you infer it or do you have knowledge about it because, e.g. it's documented?

**Comment by adrian15** [comment]
> I downloaded Fedora-LXQt-Live-x86_64-30-1.2.iso
> and that cleanly boots and has an operational keyboard and mouse.

You told us before you knew how to build your OSes from source code.
Well, as an alternative path, you might want to package Rescapp into a rpm package.

https://www.supergrubdisk.org/2017/10/22/rescapp-0-51-beta-1-has-been-released/
https://github.com/rescatux/rescapp

The most recent release is:
https://github.com/rescatux/rescapp/tree/v0.53b2
Building such a package might make @MakuSensei from https://github.com/rescatux/rescapp/issues/3 happy.

**Comment by cjg67** [comment]
Hello Adrian,

I have re-discovered a tool that I have successfully used in the past.  If you have a .deb file for rescapp then there is no need to install a different os to create the rpm.  

If you have debian installed already, all you need to do is install the package "alien" and it will automatically convert the .deb to a .rpm and will also convert .rpm to .deb

https://www.thegeekstuff.com/2010/11/alien-command-examples/

Whilst I do not mind installing a version of fedora, using alien would be the fastest way.

Regards,

Christopher.

**Comment by adrian15** [comment]
> debian-live-10.0.0-amd64-lxqt+nonfree.iso
> 
> This boots cleanly and after the desktop is fully loaded all menu items are operational with crystal clear resolution detected at 1920x1080 as default along with a working keyboard and mouse.

I have finally managed to write the so long awaited script.

Can you please check: http://rescatux.sourceforge.net/repo/README.non-free.html and tell me if there is anything to improve there?

Feel free to copy and paste the whole paragraph you would change and then write the fixed paragraph.

Waiting for your feedback.

And as the linked README says please remember that if you have any problem once rescapp starts or while you are using it then you should open an issue on the rescapp project, not the rescatux one.

**Comment by cjg67** [comment]
Hello Adrian,

The header:

But I need to help to repair my computer. Please help me!

should be:

But I need help to repair my computer. Please help me!

This paragraph:

You might want to check this older version: debian-live-10.0.0-amd64-lxqt+nonfree.iso if the newest 10.1.0 version features unusable keyboard+mouse in your specific computer model.
You can use other graphical live cd versions other than the lxqt one. But be aware that you might have to download more packages then.

Would read better if changed to:

You may want to use an older version: debian-live-10.0.0-amd64-lxqt+nonfree.iso if the newest 10.1.0 version features unusable keyboard+mouse in your specific computer model.
You can use other graphical live cd versions other than the lxqt one, but be aware that you may have to download more packages.

The following:

TIP: At this point you might want to visit this same page from your non-free live cd so that it's easier to copy and paste.

Would read better if changed to:

TIP: At this point you may want to visit this page from your non-free live cd so that it's easier to copy and paste.

The command that you have used to update and install I have not used in the past, ie:
sudo apt update
I have always used:
apt-get update
I have no idea if there is any significant difference between the two.

The sentence:

Please wait till all the packages are installed and configured.

would read better if:

Please wait untill all the packages are installed and configured.

The following:

In order to start rescapp at the menu choose Other and rescapp.

Would read better if changed to:

In order to start rescapp,  on the menu choose Other then rescapp.

The following:


    Sometimes rescapp version for amd64 repo is not kept in sync with the one that Rescatux uses (i386). If you feel this method installs a too old version of Rescapp please complain at the rescapp github issues.
    If you have problems using this method please do not open any bug at the Rescatux github issues page but instead at the rescapp github issues. Please specify in your bug reports which Debian non-free live cd filename you were using exactly.

Would read better if changed to:


    Sometimes the rescapp version for amd64 repo is not in sync with the one that Rescatux uses (i386). If you feel this method installs a too old version of Rescapp please complain on rescapp github issues.
    If you have problems using this method,  please do not open a bug on the Rescatux github issues page but instead,  on the rescapp github issues. Please specify in your bug reports which Debian non-free live cd filename you were using exactly.

Regards,

Christopher.

**Comment by adrian15** [comment]
> Fedora most certainly have added the blobs. Once the live dvd fully booted I used xterm and went to /lib/firmware and the blobs for my radeon card are there along with the blobs for the newly purchased intel based wifi card.

Ok, so here there are. I missed to read this whole paragraph. Thank you.

**Comment by adrian15** [comment]
> The header:
> But I need to help to repair my computer. Please help me!
> should be:
> But I need help to repair my computer. Please help me!

I applied your suggestions. Thank you.

**Comment by adrian15** [comment]
> The command that you have used to update and install I have not used in the past, ie:
> sudo apt update
> I have always used:
> apt-get update
> I have no idea if there is any significant difference between the two

Well, the default tool for installing packages in Debian is now apt. apt-get is also supported though. It's more like yum which feature-wise seemed to be superior to apt-get. Now I suppose that yum and apt are equal feature-wise but I actually have no clue.

**Comment by adrian15** [comment]
Can you please confirm us that you are able to start Rescapp from the Debian Live non-free LXQT 1.0.0 cd/usb?
That way we will be able to close this bug.

Thank you.

**Comment by cjg67** [comment]
Hello Adrian,

I have just tested the script, and am happy to say that it installs fine, and is totally usable.

Regards,

Christopher.

**Comment by adrian15** [comment]
> I have just tested the script, and am happy to say that it installs fine, and is totally usable.

Nice :) . Clossing the issue.
