### ISSUE TITLE
2019 Background should be improved

### ISSUE THREAD

**Issue by adrian15** [rescatux/rescatux#101]
The current svg which generates the new 2019 background can be found at: https://github.com/rescatux/rescatux/raw/e6f116eab5c2d73fa9c68119add98b24e73c83b2/live-config/bootloaders/isolinux/splash.svg .

This the manually painted draft:
![rescatux_logo_2019_002](https://user-images.githubusercontent.com/3518544/66706650-99bf2000-ed35-11e9-8d1c-c70cc12e7c46.png)

And this is the same draft modified digitally:
![rescatux_logo_2019_017](https://user-images.githubusercontent.com/3518544/66706662-cbd08200-ed35-11e9-8058-89724d7e1c40.png)

As you can see the final svg uses the former images in an horizontal way.

Will you able to create a new digital horizontal wrencho from scratch under a CC compatible license with Rescatux that features:

- Clippo dialog
- Wrench shape
- Wrencho eyes and eyebrows inspired from Microsoft Office clippo
- Linux, Windows, FreeBSD and ReactOS logos

?

**Comment by edocod1** [comment]
Hello,
I believe adding a fake dialog box is a very bad idea. It draws attention away from the actual grub, and people will certainly try to use it instead of selecting the correct entry.

**Comment by adrian15** [comment]
> Hello,
> I believe adding a fake dialog box is a very bad idea. It draws attention away from the actual grub, and people will certainly try to use it instead of selecting the correct entry.

That would fade away the Microsoft Office clippo joke.

What complementary change do you suggest in addition to the fake dialog box removal so that clippo joke can still be inferred from the image?

**Comment by edocod1** [comment]
Make it so that it doesn't look like some actual UI element. Give it some transformation (slanting, shearing or rotating) that doesn't make it look like it's usable.

**Comment by adrian15** [comment]
> Make it so that it doesn't look like some actual UI element. Give it some transformation (slanting, shearing or rotating) that doesn't make it look like it's usable.

Yeah, I guess I can blur it.

**Comment by adrian15** [comment]
Here there is the latest improvement:

![prueba-exportacion](https://user-images.githubusercontent.com/3518544/68544658-c06c8700-03c5-11ea-9e61-289e258d745e.png)

**Comment by Barbolux** [comment]
Good morning friends! That gnu doctor is very nice, he is comical and contextualizes the software very well. I came here to meet the proposal for a new art and we have this ... nut wrench? This character is not so charismatic ... looks like microsoft word clips. Can I help create a more interesting illustration?

**Comment by adrian15** [comment]
> Good morning friends! That gnu doctor is very nice, he is comical and contextualizes the software very well.

Yeah, it's true. However [the ill Tux does not convince everybody](https://twitter.com/merchygoedwig/status/1175449236399448065). And that's true seeing an ill Tux might make people think that Linux is not as strong as Windows.

> I came here to meet the proposal for a new art and we have this ... nut wrench?

His name is Wrencho.

> This character is not so charismatic ... looks like microsoft word clips.

Yes, it's kind of a clippo parody.  Clippo wasn't very useful back in the day but its idea based on Windows 1.0 Bob was brilliant. Just ask it a question and it will answer it. The Alexa, Ring and Nest predecessor.

Rescapp should aim at being able to be asked about a boot problem and answer its solution.

> Can I help create a more interesting illustration?

Yes, go ahead. The background decision is not closed.

Here there are some resources if you want to give it a go. Or feel free to upload a draft png here with a transparent background so that we can take a look.

 - [Current svg with Wrencho](https://github.com/rescatux/rescatux/blob/c92e3b3349b69673048823a4675345b6a91b29a3/live-config/bootloaders/isolinux/splash.svg)
 - [Previous svg with gnu doctor](https://github.com/rescatux/rescatux/blob/220cb25f0e38588cd4a99c6feb9a023d8abe9b7a/live-config/bootloaders/isolinux/splash.svg)

Thank you and please do not be upset if we finally discard your idea.

**Comment by edocod1** [comment]
> Yeah, it's true. However [the ill Tux does not convince everybody](https://twitter.com/merchygoedwig/status/1175449236399448065). And that's true seeing an ill Tux might make people think that Linux is not as strong as Windows.
Nothing will ever convince everybody!

Anyway, why don't we make both GNU and Linux doctors? Rescatux is used to fix Windows, Linux and whatever OS you want, by using GNU/Linux, so it'd make sense. We do not necessarely need to show the "negative" side of a doctor<->patient relationship :)

**Comment by adrian15** [comment]
> > Yeah, it's true. However [the ill Tux does not convince everybody](https://twitter.com/merchygoedwig/status/1175449236399448065). And that's true seeing an ill Tux might make people think that Linux is not as strong as Windows.
> 
> Nothing will ever convince everybody!
> 
> Anyway, why don't we make both GNU and Linux doctors? Rescatux is used to fix Windows, Linux and whatever OS you want, by using GNU/Linux, so it'd make sense. We do not necessarely need to show the "negative" side of a doctor<->patient relationship :)

That gave me an idea: Surgeon GNU, nurse tux and an open computer with its chips exposed on a hospital bed.

**Comment by edocod1** [comment]
Can you omit anything that is ill or bad?

**Comment by adrian15** [comment]
> Can you omit anything that is ill or bad?

What do you suggest instead?
Can you develop a bit further what you meant by:

> why don't we make both GNU and Linux doctors?

**Comment by edocod1** [comment]
The [previous svg](https://github.com/rescatux/rescatux/blob/220cb25f0e38588cd4a99c6feb9a023d8abe9b7a/live-config/bootloaders/isolinux/splash.svg), but Tux is a doctor too. Or just leave it GNU!

No idea, in my opinion, the less there is the better it is.

**Comment by adrian15** [comment]
> The [previous svg](https://github.com/rescatux/rescatux/blob/220cb25f0e38588cd4a99c6feb9a023d8abe9b7a/live-config/bootloaders/isolinux/splash.svg), but Tux is a doctor too. Or just leave it GNU!
> 
> No idea, in my opinion, the less there is the better it is.

Ha, ha. I might end setting up a public poll. But I would need some svgs or, at least, pngs in order to show the different options.

**Comment by edocod1** [comment]
You can find an example of a "Tux Doctor" here: https://resmedicinae.sourceforge.io/logos/doctor_tux.jpeg

**Comment by edocod1** [comment]
![rescatux svg](https://user-images.githubusercontent.com/55318198/69380772-1b965780-0cab-11ea-9cab-49d903d89dc9.png)

Something like that, maybe?

**Comment by adrian15** [comment]
> ![rescatux svg](https://user-images.githubusercontent.com/55318198/69380772-1b965780-0cab-11ea-9cab-49d903d89dc9.png)
> 
> Something like that, maybe?

Yeah, I can use this image for the hipothetic future poll.
Thank you!

**Comment by adrian15** [comment]
Here there is another background based on @edocod1 idea:

![rescatux-0 72-beta7-preview](https://user-images.githubusercontent.com/3518544/70392360-b008f580-19df-11ea-9af9-f3002789202b.png)

**Comment by edocod1** [comment]
Nice!
- the circle thing tux is wearing (no idea how it is called in english) is cut
- If you notice in my image the line coming from gnu's uniform was right on the edge of tux to give the impression of them overlapping, but here there's a cut that makes it apparent the images are incorrectly cut
- i'd add some padding at the sides of the uefi boot menu entries.

**Comment by adrian15** [comment]
> Nice!
> 
> * the circle thing tux is wearing (no idea how it is called in english) is cut
> * If you notice in my image the line coming from gnu's uniform was right on the edge of tux to give the impression of them overlapping, but here there's a cut that makes it apparent the images are incorrectly cut
> * i'd add some padding at the sides of the uefi boot menu entries.

Go ahead and fork the master branch so that you can work on https://github.com/rescatux/rescatux/blob/master/live-config/bootloaders/isolinux/splash.svg .

Then make a pull request so that I can take a look at your new svg.

Thank you.

**Comment by edocod1** [comment]
Sorry, i do not have idea on how to make a pr. I don't use github.
Anyway, i attached you a zip file of the svg.
[index.svg.zip](https://github.com/rescatux/rescatux/files/3936617/index.svg.zip)

**Comment by adrian15** [comment]
> Sorry, i do not have idea on how to make a pr. I don't use github.
> Anyway, i attached you a zip file of the svg.
> [index.svg.zip](https://github.com/rescatux/rescatux/files/3936617/index.svg.zip)

Ok, updated with your suggested svg.

**Comment by Barbolux** [comment]
> That gave me an idea: Surgeon GNU, nurse tux and an open computer with its chips exposed on a hospital bed.

this idea is awesome! thumbs up.

**Comment by adrian15** [comment]
The current background seems nice. Closing this.
