### ISSUE TITLE
Error boot 1 and 2 on iso ???

### ISSUE THREAD

**Issue by thamermousa** [rescatux/rescatux#110]
Error 1 rescatux-0.73.iso
![IMG_20200617_170845](https://user-images.githubusercontent.com/3912594/84956805-8e14cc00-b102-11ea-8ff1-1ec666ed9e93.jpg)

Error 2 super_grub2_disk_hybrid_2.04s1.iso
menu.lst
wubildr.cfg

 `
> 
# ============= مجموعة استرجاع البووت Grub2 في موقع supergrubdisk ===========
# http://www.supergrubdisk.org/category/download/rescatuxdownloads/rescatux-stable/
# http://www.supergrubdisk.org/category/download/supergrub2diskdownload/super-grub2-disk-stable/

# رئيسي جديد 2020 خيارات متعددة منها البوت وحذف كلمة السر للويندوز ومن نفس موقع supergrub2
# rescatux-0.73 مشاكل الاقلاع والدخول على الانظمة
title rescatux-0.73\n\nrescatux-0.73 ( 11.9 M.B )\n\n\t\t\tArabicMicrosoft@gmail.com
ls /W81X/images77/ISO77/rescatux-0.73.iso || find --set-root /W81X/images77/ISO77/rescatux-0.73.iso
map --heads=0 --sectors-per-track=0 /W81X/images77/ISO77/rescatux-0.73.iso (0xff) || map --heads=0 --sectors-per-track=0 --mem /W81X/images77/ISO77/rescatux-0.73.iso (0xff)
map --hook
chainloader (0xff)

# رئيسي جديد 2020
# super_grub2_disk_hybrid_2.04s1 مشاكل الاقلاع والدخول على الانظمة
title super_grub2_disk_hybrid_2.04s1\n\nsuper_grub2_disk_hybrid_2.04s1 ( 11.9 M.B )\n\n\t\t\tArabicMicrosoft@gmail.com
ls /W81X/images77/ISO77/super_grub2_disk_hybrid_2.04s1.iso || find --set-root /W81X/images77/ISO77/super_grub2_disk_hybrid_2.04s1.iso
map --heads=0 --sectors-per-track=0 /W81X/images77/ISO77/super_grub2_disk_hybrid_2.04s1.iso (0xff) || map --heads=0 --sectors-per-track=0 --mem /W81X/images77/ISO77/super_grub2_disk_hybrid_2.04s1.iso (0xff)
map --hook
chainloader (0xff)

# رئيسي القديم Old
# super_grub2_disk_hybrid_2.00s2 مشاكل الاقلاع والدخول على الانظمة
title super_grub2_disk_hybrid_2.00s2\n\nsuper_grub2_disk_hybrid_2.00s2 ( 11.9 M.B )\n\n\t\t\tArabicMicrosoft@gmail.com
ls /W81X/images77/ISO77/super_grub2_hybrid_2.iso || find --set-root /W81X/images77/ISO77/super_grub2_hybrid_2.iso
map --heads=0 --sectors-per-track=0 /W81X/images77/ISO77/super_grub2_hybrid_2.iso (0xff) || map --heads=0 --sectors-per-track=0 --mem /W81X/images77/ISO77/super_grub2_hybrid_2.iso (0xff)
map --hook
chainloader (0xff)

title
root

`

**Comment by englishextra** [comment]
have the same issue with rescatux-0.73.iso  // dual boot win10 1909 and fedora 32 kde // grub-customizer made a boot menu with fedora and windows 10 entries. added rescatux-0.73.iso to bootable flash using YUMI 2.0.2.0

**Comment by thamermousa** [comment]
>  with YUMI 

The problem I have other programs to use
It is difficult to put this program


CPU : 
Intel Processor i5 8400 @ 2.80GHz up to 3.000GHz

RAM : 
32.000 GB 3000MH XPG 8GBx4Pin

Motherboard : 
ASUSTeK COMPUTER INC. TUF Z370-PLUS GAMING (LGA1151)

Graphics : 
NVIDIA GeForce GTX 1060 6GB

Storage : 
HDD 931GB Seagate ST1000DM010-2EP102 (SATA)
M.2 447GB KINGSTON SA1000M8480G (SATA-2)

The device I have is somewhat modern , I tried this tool which "Ventoy" works well in some cases 
https://www.ventoy.net/en/download.html

But i just want to use this boot grub4dos

Thank you

**Comment by englishextra** [comment]
@thamermousa I am pretty sure that 0.73 needs SYSLINUX not grub from RAM or grub partition 4 while older releases like 0.41 and 0.53 can be bootable along with other isos flushed with YUMI on one usb stick.

That's the difference

also with rescatux 0.73 flushed with balenaEtcher-Portable-1.5.101.exe you will get a fully occupied USB stick that can be not visible from Windows or only two service folders can be visible which means it is SYSLINUX

**Comment by thamermousa** [comment]
In old matherboard super_grub2_disk_hybrid_2.00s2.iso It works great and fast , in grub4dos

And on the same files in grub4dos , But in a new motherboard it does not work

 Because I always edit this menu.lst file and it is a major boot for me in file iso

And this BOOTICEx64 tool is important for me to retrieve the MBR on grub4dos


![2020-07-28_085824](https://user-images.githubusercontent.com/3912594/88624940-8b69a700-d0b0-11ea-9f70-eb855acf277b.jpg)


I just want to play these files ,  grldr and grldr.mbr and menu.lst and file iso , Using MBR on grub4dos

Waiting for the update so that they might find a solution to the problem

Thank you @englishextra

**Comment by adrian15** [comment]
> UPD Well it worked with etcher - single iso to one usb i mean 0.73 but it wont work on older machines. For that I used 0.41 and 0.53 that can be added with YUMI along with other ISOs on a multiboot usb stick

Well, I think that Rescatux needs a 686 processor at minimum. You might have quite an old machine.
I'm not going to backport a 586 processor in order to support your old machine.

**Comment by adrian15** [comment]
> Using MBR on grub4dos

Boot from grub4dos is not supported by us.
