### ISSUE TITLE
Rescatux does not run live distro

### ISSUE THREAD

**Issue by pgtipz** [rescatux/rescatux#112]
Hi, thanks for your work, first of all!

I have not been able to start Rescatux live system desktop from the usb.iso, of version.73, which I have successfully installed on thumbdrive and the checksum has passed. 

The logo 'Rescatux' and options open on screen at first, but then once I choose an option, 
the screen defaults to a black screen with copyright info and debian terminal. At the top, the message is: login user [automatically], but the live desktop does not run, nor does Rescapp. 
I wish it did!

Please advise. Cheers!

Custom box: AMD Rizen 1500X quad core; 19GB RAM; HDD 1 - Windoze10_64; 
HDD2 - Manjaro 20.0.03; KDE Plasma; Fibre BB;

**Comment by LVPols** [comment]
Hi,

I also get exactly this screen as you describe.

My PC: AMD Ryzen 2600X, AMD Radeon 5700 GPU;
SSD - Arch linux with xfce;
HDD - Windoze 10_64 which cannot boot :(

**Comment by adrian15** [comment]
That's why the Non free Rescatux page was invented for.

Please check: https://rescatux.sourceforge.net/repo/README.non-free.html .
