### ISSUE TITLE
rescatux starting problem

### ISSUE THREAD

**Issue by resuser5** [rescatux/rescatux#113]
![20201004_135313](https://user-images.githubusercontent.com/72342042/95014664-fa372380-0650-11eb-9d6f-e610cbfcca56.jpg)

**Comment by LVPols** [comment]
I also get exactly this screen.

**Comment by CleanHit** [comment]
Is this going to be solved? I'm having the same issue with Rescatux 0.73 on my AMD Ryzen 4800HS With NVIDA 1660 TI MAX-Q machine.

**Comment by AlexIsOK** [comment]
Same here.  Older versions of the OS seem to work though.

**Comment by SDHU-4** [comment]
Bonjour,

J'ai le même problème !!!! 
( j'ai essayé avec les versions 0.73 et la dernière 0.74 )

Je ne SAIS PLUS QUOI FAIRE ...???
Merci beaucoup.

**Comment by SDHU-4** [comment]
Hello,

I have the same problem !!!!
(I tried with versions 0.73 and the latest 0.74)

I do not know what to do ...???
Thank you very much.

**Comment by adrian15** [comment]
That's why the Non free Rescatux page was invented for.

Please check: https://rescatux.sourceforge.net/repo/README.non-free.html .
