### ISSUE TITLE
Rescatux not able to boot 

### ISSUE THREAD

**Issue by koravadi** [rescatux/rescatux#114]
Hello,

I am getting this error once I selected the auto detect.. let me know if some one can help why I am getting this error.. if I use super grub disk I can boot the Ubuntu.. I am using del i7559 laptop.

![0B84B304-36D7-4CA9-97CA-69D6314AC467](https://user-images.githubusercontent.com/16981298/95911881-09fce900-0d70-11eb-93bf-0addd2729f27.jpeg)

![image](https://user-images.githubusercontent.com/16981298/95912358-bb038380-0d70-11eb-8edd-181e3910d229.jpg)

**Comment by adrian15** [comment]
You might be able to workaround your problem by using Non free Rescatux page.

Please check: https://rescatux.sourceforge.net/repo/README.non-free.html .

**Comment by adrian15** [comment]
There has not been any more feedback into this issue when the reporter was asked to provide feedback.

Hence we are closing this bug.
