### ISSUE TITLE
Rescatux 0.74 won't boot, but 0.73 will

### ISSUE THREAD

**Issue by AlexHimself** [rescatux/rescatux#117]
I'm still working on recovering a machine, so not sure how to collect logs, but I tried Etcher and Rufus, flashed 3 different USB drives with 0.74 and let it try and start for 20+ min and it would sometimes start displaying loading progress, but then say there's an issue with the Debian Live CD and to file a bug.

Downloaded 0.73 and flashed USB drive and I was up and running in 2 minutes.

Computer is AMD 32-core, 128 GB RAM, 2 TB NVMe SSD so performance shouldn't be a problem.

**Comment by AlexHimself** [comment]
I need to collect more info before being sure this is a .74 v .73 issue

**Comment by adrian15** [comment]
Etcher should be fine for doing tests because it's the default supported method for putting Rescatux into an USB.
