### ISSUE TITLE
File system check (force fix) for xfs/btrfs

### ISSUE THREAD

**Issue by arozenfe** [rescatux/rescatux#118]
The force filesystem fix always runs the same command:
`fsck -fy <device>`

For some filesystems, such as BTRFS or XFS, there are other tools required to repair a damaged filesystem, so the `fsck` command will exit with 0, and the app will always say that "Filesystem check with automatic fix was OK! :)".

For btrfs:

```
root@debian:~# fsck -fy /dev/sda1 ; echo $?
fsck from util-linux 2.33.1
0
```
```
root@debian:~# fsck /dev/sda1
fsck from util-linux 2.33.1
If you wish to check the consistency of a BTRFS filesystem or
repair a damaged filesystem, see btrfs(8) subcommand 'check'.
```

For xfs:

```
root@debian:~# fsck -fy /dev/sda4 ; echo $?
fsck from util-linux 2.33.1
/usr/sbin/fsck.xfs: XFS file system.
0
```
```
root@debian:~# fsck /dev/sda4 
fsck from util-linux 2.33.1
If you wish to check the consistency of an XFS filesystem or
repair a damaged filesystem, see xfs_repair(8).
```

I confirmed the same results on corrupted filesystems, there was no check running on them.

**Comment by adrian15** [comment]
> For some filesystems, such as BTRFS or XFS, there are other tools required to repair a damaged filesystem, so the fsck command will exit with 0, and the app will always say that "Filesystem check with automatic fix was OK! :)".

Could you please provide some snippets about that?

Maybe one snippet about the right way of doing the fsck in an specific fs?

And then if you know how, else I will check, well, how to detect which fs it is.

Thank you!

**Comment by adrian15** [comment]
There has not been any more feedback into this issue when the reporter was asked to provide feedback.

Hence we are closing this bug.
