### ISSUE TITLE
Impossible de lancer RESCATUX...???

### ISSUE THREAD

**Issue by SDHU-4** [rescatux/rescatux#119]
Bonjour,

j'ai un pote qui m'a ramené un portable packard bell (assez vieux) sous W10 ou 7 (mais je pense que c'est W10) pour faire de la maintenance .
Comme il ne se rappelle plus du password (session user) , je suis donc bloqué lors de la demande (session user) du password. (et bien sur ni le passwd admin )

Je me suis donc crée une clef usb avec Rescatux en bootable
j'avais déjà essayé il y a quelque temps avec la version V 0.73 maintenant avec la 0.74, mais ça me fait toujours le même problème : 
j'ai bien la premiere image (le logo: la vache avec le pingouin) puis une fenetre noire apparait, je fais enter et des lignes apparaissent  (je pense que ce sont des commandes du noyaux linux ???)
puis **il s'arrête (bloqué)  à chaque fois sur** :

....
...
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent permitted by applicable law
-   (avec ce tiret clignotant)

J'ai refait la clef usb, j'ai même également utilisé une autre clef, 
j'ai même réessayé sur un autre portable (Surface Microsoft W10/64b), cette fois-ci il s'arrête sur la ligne:
....
....
SQUASHFS:unable read page, block 11db9083

Et il ne se passe plus rien..bloqué la dessus.

Si quelqu'un a des idées sur ce problème ?
Merci beaucoup car je galère depuis très longtemps avec ça !!!!    **Je ne suis jamais arrivé à le lancer.**..-(((

**Comment by SDHU-4** [comment]
Bonjour,

Toujours pas d'idées...??

**Comment by lonnie44** [comment]
Hi, not sure if still a question but whatever..
If you got the screen with '_Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent permitted by applicable law_' that means Debian booted just fine, but if you are not presented the desktop (GUI) that is where it gets stuck.
However you can move to a different terminal with [ Ctrl + Alt + F2 ], you will see a terminal prompt and you can switch to the root user with @sudo -i@ and get started, like mount your ntfs in /mnt and copy/rename/edit stuff (on the command-line), to regain access.

**Comment by adrian15** [comment]
> SQUASHFS:unable read page, block 11db9083

Use a non broken USB device.
