### ISSUE TITLE
AMD R600 RADEON *ERROR*

### ISSUE THREAD

**Issue by ETENNE** [rescatux/rescatux#120]
Unable to use RESCATUX 0.74 with ATI RADEON HD 5670 video card.
During boot the following message appears:

"[drm: radeon_pci_probe [radeon]] * ERROR * radeon kernel modesetting for R600 or later requires firmware installed

After that the maximum usable resolution turns out to be 700x400
unreadable and unusable :-(

**Comment by adrian15** [comment]
That's why the Non free Rescatux page was invented for.

Please check: https://rescatux.sourceforge.net/repo/README.non-free.html .
