### ISSUE TITLE
UEFI Mode unable to boot

### ISSUE THREAD

**Issue by MrGamy** [rescatux/rescatux#122]
When trying to boot rescatux in UEFI mode, it gets stuck while booting. Tried different multiboot options (Ventoy, YUMI, UNetbootin) as well as single boot options (dd, Rufus) without luck. BIOS Boot works fine, but afaik does not work on UEFI Windows.

I can see a failure in loading Bluetooth firmware, but that should not halt overall boot, right?

 
![1](https://user-images.githubusercontent.com/8639512/188889270-befb5b32-e6e3-4a36-914c-65e7bf118ce7.jpg)
![2](https://user-images.githubusercontent.com/8639512/188889280-a712073d-a3bc-44f8-90dc-b54c78da9f69.jpg)
![3](https://user-images.githubusercontent.com/8639512/188889294-83dd312d-a8ab-47b1-8360-1f8db4d0d563.jpg)
![4](https://user-images.githubusercontent.com/8639512/188889287-57dc4d9e-c5d8-429d-ab92-29f0292b32c4.jpg)

**Comment by nmarks413** [comment]
I have the same issue on a UEFI system

**Comment by lonnie44** [comment]
Looks like Debian started fine, but X (LXQT desktop) failed.
Can you switch to another terminal [ Ctrl + Alt + F2 ] ?
If so, you could try to run **startx** and check why it won't start (or try solving your issue via cli).

**Comment by adrian15** [comment]
That's why the Non free Rescatux page was invented for.

Please check: https://rescatux.sourceforge.net/repo/README.non-free.html .

**Comment by PallStar** [comment]
Is the Non-Free version still available somewhere? The SourceForge repo is showing a 404 and I am using an nVidia 3080Ti and the nouveau driver is not detecting it.
