### ISSUE TITLE
0.73 boots on dell precision m6800, 0.74 does not

### ISSUE THREAD

**Issue by thotsputin** [rescatux/rescatux#123]
im booting from ventoy (UEFI). 0.74 throws

```
BOOTING KERNEL FAILED: Invalid Argument
boot:

```
error on boot. pressing any key goes to initial "login" screen, making any selections on that screen throws the aforementioned or some different error.

I can load 0.74 on a USB the regular way and try booting legacy later. can also provide mor
![IMG_20220911_212300~(1)](https://user-images.githubusercontent.com/113323011/189565640-e1815ebd-4541-4380-95ce-49b3dcdf8e19.jpg)
e.specs if u want them.

0.73 works fine as expected and usual

**Comment by adrian15** [comment]
It's a Ventoy issue not from Rescatux.

If you put the USB the regular way in two different USB devices and it still does not work then you can complain.
