### ISSUE TITLE
Rescuatux is still unable to boot on UEFI Systems

### ISSUE THREAD

**Issue by ber999** [rescatux/rescatux#125]
Rescuatux is still unable to boot on UEFI Systems
Message is; Window Verification failed Security violation

**Comment by adrian15** [comment]
Rescatux needs to be built with a newer Grub 2.06.

Some older Grub 2.06 versions are affected by a vulnerability and older keys that signed those Grub versions are revoked by the UEFI firmware.

As a consequence you cannot boot from some older Secure Boot enabled live cds like Rescatux.

**Comment by adrian15** [comment]
Working on a new Rescatux version in 2024 so closing this.
