### ISSUE TITLE
Rescatux is using a very old kernel 4.19

### ISSUE THREAD

**Issue by kneutron** [rescatux/rescatux#126]
The last available release from 2021 is using kernel 4.19.208-1 and cannot fix / mount XFS root partition from recent kernels. Can we please get a new Rescatux release?  If not for $REASONS, please contact me as I have some free time lately and am willing to help build and test.
![Screen Shot 2024-02-13 at 4 36 06 AM](https://github.com/rescatux/rescatux/assets/50146127/995bff18-f6d3-488a-808e-8d26841ef59a)

**Comment by adrian15** [comment]
Going to work on releasing an updated Super Grub2 Disk.
After that I will be working on updating Rescatux, probably basing it on Debian 12.
