### ISSUE TITLE
Non-free page is a 404

### ISSUE THREAD

**Issue by Manchovies** [rescatux/rescatux#127]
Your link to the non-free download page does not open:
https://rescatux.sourceforge.net/repo/README.non-free.html

I cannot find a download anywhere and installing Rescapp gives me an import error about PyQt5. I installed that but now it can’t import one of the modules. I can upload errors later but really I just want the ISO for easy use.

**Comment by adrian15** [comment]
Thank for your report.

This has been fixed.
