### ISSUE TITLE
Please replace MD5 checksum with SHA256 checksum, signature and PGP key

### ISSUE THREAD

**Issue by MarkRijckenberg** [rescatux/rescatux#95]
Hi,

I noticed that your team still distributes MD5 checksums for the .iso images for RescaTux at – for example – the following URL:

https://sourceforge.net/projects/rescatux/files/rescatux_0_41_b1/

May I kindly ask you to take a look at the following links?

https://en.wikipedia.org/wiki/Secure_Hash_Algorithms

https://github.com/gobolinux/LiveCD/issues/8

MD5, SHA-0 and SHA1 are all vulnerable to collision attacks.

SHA256 (or SHA512) is now the standard (for the moment).

I highly recommend dropping the use of MD5 and replacing it with only SHA256 (or SHA512).

I am simply using Qubes OS as an excellent point of reference, which uses SHA256 and SHA512.

https://www.qubes-os.org/security/verifying-signatures/

https://www.qubes-os.org/downloads/

Concerning the use of Bittorrent, could you please read this?

https://www.ghacks.net/2016/02/21/linux-mint-hacked-iso-images-compromised/

If you put the .iso image and corresponding SHA256 checksum file, signature and PGP key in a .zip file and distribute it immediately via Bittorrent BEFORE hosting it on a website, hackers will probably not be able to compromise the integrity of the .iso image, because the SHA256 checksum in the Bittorrent file is much harder to alter than one stored on a website. Furthermore, you then have the option of comparing the SHA256 value in the .torrent file with the value on the website. This goes even further than what most  GNU/Linux distributions actually do….

“The reason is simple; popular torrents are distributed from several seeders and peers, and once they are in circulation, it is not possible to manipulate the data, say replace it with a hacked image.”

Kind regards,

Mark Rijckenberg

**Comment by adrian15** [comment]
SHA256 checksum was added finally in the past.

Closing this.
