### ISSUE TITLE
new 3d logo for rescatux

### ISSUE THREAD

**Issue by tecan** [rescatux/rescatux#97]
[logo.zip](https://github.com/rescatux/rescatux/files/2753691/logo.zip)
credits to blendswap for the rigged tux model

**Comment by tecan** [comment]
![rescatux](https://user-images.githubusercontent.com/172564/51092216-0d55e180-1752-11e9-84fb-37c923637c09.png)

**Comment by RustyRaptor** [comment]
That's kinda nice actually.

**Comment by tecan** [comment]
https://netpipe.ca/?page_id=2486

**Comment by RustyRaptor** [comment]
I haven't use a CD/DVD for booting in quite some time haha.

**Comment by adrian15** [comment]
Thank you for your work.
I'm currently satisfied with the current background.

We need an app icon if you want to take it a look. Not sure what to put there.
Maybe a lifesaver.

Open a new issue in https://github.com/rescatux/rescapp/issues if you want to contribute there.

**Comment by adrian15** [comment]
@tecan : You might be interesred on contributing on https://github.com/rescatux/rescatux/issues/101 .
