### ISSUE TITLE
Rescatux 0.71-beta7 radeon issue

### ISSUE THREAD

**Issue by cjg67** [rescatux/rescatux#98]
Hello,

I just downloaded rescatux and found after burning it to cd, that it will not boot on my system.  I have tried the "auto" and both the amd64 failsafe and normal.  It is due to the fact that the R600 firmware required for my built in video card has not been included in the image.

Could this issue be fixed so that I can try this?

Regards,

Christopher.

**Comment by cjg67** [comment]
Wish I had known this was a DEAD project before wasting my time downloading and burning a cd.

**Comment by adrian15** [comment]
> Wish I had known this was a DEAD project before wasting my time downloading and burning a cd.

Thank you for your feedback.
Now I know that I have to add one of those issue template where I state this is a free as an freedom and free as free beer project. So that you shouldn't expect an answer in less than 24 hours.

I think I will be able to answer your issue either today or tomorrow.

**Comment by adrian15** [comment]
* Test 1

https://cdimage.debian.org/cdimage/weekly-live-builds/amd64/iso-hybrid/debian-live-testing-amd64-lxqt.iso
Please test the weekly **normal** debian live image with the **default boot option**.
Does it boot ok for you? Or do you get a black screen instead?

* Test 2

https://cdimage.debian.org/cdimage/weekly-live-builds/amd64/iso-hybrid/debian-live-testing-amd64-lxqt.iso
Please test the same weekly **normal** debian live image with the **failsafe boot option**.
Does it boot ok for you? Or do you get a black screen instead?

* Test 3

https://cdimage.debian.org/cdimage/unofficial/non-free/images-including-firmware/weekly-live-builds/amd64/iso-hybrid/debian-live-testing-amd64-lxqt+nonfree.iso
Please test the weekly **non-free** debian live image with the **normal boot option**.
Does it boot ok for you? Or do you get a black screen instead?

* Test 4

I build Rescatux + non-free : Well, that's not going to happen yet. Adding non-free packages to Rescatux goes against FSF philosophy.

**Comment by adrian15** [comment]
> I just downloaded rescatux and found after burning it to cd, that it will not boot on my system.
> I have tried the "auto" and both the amd64 failsafe and normal.
> It is due to the fact that the R600 firmware required for my built
> in video card has not been included in the image.

What's the exact output you get in the screen?
Do you get a completely black screen?
Or is it anything written there?
What exactly?

**Comment by adrian15** [comment]
> I have tried the "auto" and both the amd64 failsafe and normal.

I have been reading more about the:
```
radeon kernel modesetting for R600 or later requires firmware-amd-graphics
```

error which I don't know if it is yours.

The nomodeset option on failsafe mode should avoid triggering it. Not sure why it appears. Maybe it's a bug triggered by this package: https://packages.debian.org/buster/xserver-xorg-video-radeon .

1. You might want to try adding:
```
modprobe.blacklist=radeon
```
as a kernel boot parametre.

TAB or ESC in non-UEFI mode / isolinux.
Or 'c' in UEFI mode / grub .

and gives us feedback to us.

2. If you ever get an error. Can you change from tty thanks to: CTRL+ALT+F1, CTRL+ALT+F2, and so on?

Thank you very much!

**Comment by cjg67** [comment]
Hello,

 

Well I have done the requested testing. 

 

1) The current beta of Rescatux hard locks when using failsafe mode.  IE, ctrl+alt+del do not work, so I have to use the reset button.  This happens either with black listing the radeon driver, which is not set any way for the failsafe or not.

 

2) Made a little more progress with the normal amd64 boot.  This time I was determined to see what would happen when I attempted to boot into the normal mode.  I first tried it again without the blacklist option and had to wait a full three minutes for anything to happen on the ctrl+alt+f1 etc.  When the boot cycle finished, the screen keeps flicking on and off.  It did eventually drop me into the logged in "user" account.  I found out after checking the log files that the xserver had failed to start.  I tried starting it as the normal user and got a failed to start server message, so I then switched to root via sudo su, and from there issued the startx command.  It was then the three minute waiting game.  When a single icon appeared on the bottom of the screen, I knew that something had indeed booted correctly.  I found out that it was the menu.  The screen keeps flicking off and on even within the desktop environment.

 

The menu names are totally unreadable.

 

3) I then did as requested and tried the lxqt version of the weekly builds.  This does boot far better than the current rescatux, but it too is buggy.  For example I had to again ussue startx to get it to run.  This time the appearance of the desktop was very quick.  There is no flicking on and off of the screen, though the menu text is only a little bit better than rescatux.

 

4) I then downloaded the non quicktime version of the iso, ie debian-live-testing-amd64-lxde.iso, from the 20th may.  This version is the best for you to base any rescatux work on.  It boots cleanly and the desktop is at least good enough to see the menu items and work with.  The screen resolution is the issue when not using the proprietory drivers.  But as this is not going to be used as an everyday desktop it would certainly be acceptable for anyone with an on-board graphics chip.

 

5) I tried the lxqt+nonfree version, and that just will not get past verifying the drm pool.  Left it for about 4 mins and flagged it away when nothing happened.

 

Hopefully this has given you some insight as to what is going on with regards to rescatux on my type of desktop computer.

 

Regards,

 

Christopher


Sent: Monday, May 20, 2019 at 1:50 AM

**Comment by adrian15** [comment]
* Normal debian-live-testing-amd64-lxde.iso
* Normal debian-live-testing-amd64-lxde.iso

**Comment by adrian15** [comment]
1) Can you please confirm me that I understood your tests:

* Normal debian-live-testing-amd64-lxqt.iso : Needs startx so that desktop is shown.
* Non-free debian-live-testing-amd64-lxqt.iso : It will not get past verifying the drm pool
* Normal debian-live-testing-amd64-lxde.iso : Boots into desktop ok.
* Non-free debian-live-testing-amd64-lxde.iso : Not tested.

?

2) If you want to make more tests you would have to test normal buster stable images.
* https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/
* https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/debian-live-10.0.0-amd64-lxde.iso
* https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/debian-live-10.0.0-amd64-lxqt.iso

If lxde version works for you but not the lxqt version then it might be a problem with SDDM. And that would need to be reported to Debian itself.

But let's not go too fast :) .

Let's wait your feedback first.

**Comment by cjg67** [comment]
Sent: Wednesday, August 28, 2019 at 6:07 AM

**Comment by adrian15** [comment]
> I did not expect so many MONTHS to pass between replies.
I understand.

> I have a total BITCH of a bios in order to try and boot from a usbstick.  I have to spend HOURS fighting to get it to work.
That's unfortunate.

> Sorry but I do not need any more stress in my life, so I guess I will just file away not to use rescatux.
Ok, if you ever use a newer version of Rescatux and it works for you feel free to open a new issue refering to this one to keep us informed.

I'll close the bug.

**Comment by adrian15** [comment]
Hi @cjg67 . I just received this new issue: [Versions Newer than 51b3 won't run](https://github.com/rescatux/rescatux/issues/103) .

I would like to know: Did you try Rescatux 0.51-beta3 in your system? Does it boot properly if you try it nowadays?
